---
- block:
  - name: install backup related packages
    apt: "name={{ item }} state=latest"
    with_items:
      - borgbackup
      - rclone
      - sshfs
      - nfs-common
  tags:
    - backuptools
